### ISSUE TITLE
Shim detection/creation is broken

### ISSUE THREAD

**Issue by Gerrit-K** [zinit-zsh/z-a-bin-gem-node#4]
After a recent update, the shim detection/creation seems to be broken (at least for installing new plugins).

I tested with:
```bash
zi wait'0a' lucid has'kubectl' from'gh-r' for \
 bpick'*kubectx*' \
 id-as'kubectx' \
    sbin'kubectx' ahmetb/kubectx \
 bpick'*kubens*' \
 id-as'kubens' \
    sbin'kubens' ahmetb/kubectx \
```

Running a `git bisect` reports that https://github.com/zinit-zsh/z-a-bin-gem-node/commit/47ec1433077493c72db342e4d64b0cb8933de633 is the culprit. 

* `uname -a`: `Darwin MacBook-Pro.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin`
* `zsh 5.8 (x86_64-apple-darwin19.3.0)` (from brew)

**Comment by psprint** [comment]
It's fixed, thanks.

**Comment by psprint** [comment]
I've pushed new commits, you need to `self-update`.

**Comment by Gerrit-K** [comment]
Ah I see. Yes, it works again, thanks 👍
