### ISSUE TITLE
Split sbin ice into separate handler

### ISSUE THREAD

**Issue by NICHOLAS85** [zinit-zsh/z-a-bin-gem-node#6]
Currently, the sbin ice is handled using the %atpull hook recreating every shim on every `zinit update`. An idea could be to only run it using the atpull hook in a separate handler so that the shims are only recreated when needed, getting rid of the extra messages on every update.

**Comment by psprint** [comment]
Yes I can agree that the messages can be annoying. To prevent the shims from being recreated no extra handler is needed – they're recreated intentionally, I've often occurred a situation when this was needed, to my surprise not-recallable now, however. I can mute the message… And I will, now… BTW, have you seen `-q` option for `update`?

**Comment by NICHOLAS85** [comment]
Ah I didn't know it was being recreated purposefully, just thought it'd be a useful suggestion to not have it being run unnecessarily. And yes I've seen the -q option, thanks for being diligent in implementing it across your annexes and code!

**Comment by NICHOLAS85** [comment]
I do wonder why it does need to be recreated just out of curiosity. It should be persistent being that $ZPFX/bin is included in $PATH unlike the fbin and similar ices that need to be created every session. Anyways I'm loving the growth I'm seeing with all these projects and learning from them. Congrats on the Zplugin->Zinit rename

**Comment by psprint** [comment]
Thanks, I'm also glad about the rename :) It wasn't easy but easier than anticipated. Trying now hard to recall the purpose of the shim recreation I would state that: sometimes the ZPFX/bin dir can be deleted or the shim overwritten by e.g.: a command that copies the actual binary.
