### ISSUE TITLE
handler filenames with colons make it impossible to use the Plugin under Windows with msys/mingw/cygwin

### ISSUE THREAD

**Issue by seflue** [zinit-zsh/z-a-bin-gem-node#7]
I just imported my zshrc from my private Linux system in my msys environment on a Windows system at work and wondered why all was blowing up. And the reason was, that the zinit annex repositories couldn't be cloned - because some filenames contain colons, which is not allowed under windows.

Please consider to rename them to a more complient form so your plugin is also usable for Windows expats (I wish, I could use a Linux system at work, but thats currently not possible and under WSL the filesystem is (currently) too slow to use Git in a reasonable way).

**Comment by psprint** [comment]
Bad news… I'll have to update my paradigm of calling handler-like functions prefixed with a colon… Any idea maybe for such symbol? It can be Unicode. The colon's rationale was: to fill the gap in between the dots – by the handler function, which gets registered somewhere…

**Comment by psprint** [comment]
The available symbols are:

≠²³¢€½§·«»–πœę©ß←↓→óþ
ðæŋ’ə…
„”µ≤≥
¡¿£¼‰∧≈¾±°—
ÐÆŊ•Ə˝ˇ
‘“∞×÷˙

They're easily typeable by right Alt. Now only a rationale behind one is needed…

**Comment by seflue** [comment]
Thank you for considering a change.

Thinking about your question - I'm not sure if I would pay the price of using a non-ascii and restricted character a function or variable name to express a rational with just one character. Your handler functions already have a `-handler` suffix, so it's already clear for the reader, that you call a handler. And what the handlers are doing and how it is mentioned in your project seems to be better placed in a comment or an architecture documentation than an obscure symbol used in the function name. Personally I would never accept other characters then `[a-z][A-Z][0-9]` and `_` in a code review (and even for the numbers there is a really good reason needed to be used). The risk of painfull exceptions where a special character does not work would be too high for me.

**Comment by psprint** [comment]
Zsh supports absolutely any string as a function name, because absolutely any string can be a **file** name… Think of it – if there would be an exception in the name of the callables, then how would you run a script called "→abcd"? There are *no* exceptions, the function can be called even as a sequence of the null bytes:

```
❯ $'\0'() print hello
❯ $'\0'
hello
```

Because of this freedom I see no reason to not make a use of the non-ascii characters.

**Comment by seflue** [comment]
Only because it is possible, doesn't mean it is a wise or even just a practical decision, to make use of this possibility. Don't get me wrong, it is your project and you have the absolut freedom to decide what seems reasonable for you. And if you choose a solution, which let me use your project under Windows, I'm very grateful. But if you ask me for my opinion about this decision, I would ommit any character which is only suspicious to cause problems. May it be a clash with filenaming conventions of an OS or just a character which is hard to type on a standard keyboard. I had enough problems with Unicode support in different programming languages in my carreer to get a bad gut feeling about "Ok, colons do not work on windows, let's try some Unicode character."

**Comment by psprint** [comment]
I'm maintaining and developing a Zsh plugin standard where I recommend a set of function-prefixes, see [here](http://zdharma.org/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html#namespacing). It contains a motivation for such prefixes. I'll go for the unicode character, as at worse what can happen is a need to copy-paste with the mouse the function name once or twice during development :)

**Comment by psprint** [comment]
The annex should now work under Windows. (I've went for `→`, which is RAlt-i on my keyboard; the rationale is quite nice – the arrow denotes the calling-back being done in an automatic fashion).
